name: AmiComponentRunPlaybookReboot
schemaVersion: "1.0"

parameters:
  - ExtraVars:
      type: string
  - PlaybookPath:
      type: string

phases:
  - name: build
    steps:
      - name: WriteExtravars
        action: ExecuteBash
        inputs:
          commands:
            - |
              cat << 'EOF_EXTRAVARS' > /tmp/extravars.json
              {{ ExtraVars }}
              EOF_EXTRAVARS

      - name: RunPlaybook
        action: ExecuteBash
        inputs:
          commands:
            - |
              ansible-playbook \
                -i localhost, \
                -c local \
                -e 'ansible_python_interpreter=/usr/bin/python3' \
                -vvv \
                -e @/tmp/extravars.json \
                {{ PlaybookPath }}

      - name: Reboot
        action: Reboot
        onFailure: Abort

      - name: PostReboot
        action: ExecuteBash
        inputs:
          commands:
            - echo 'The system has restarted successfully.'
